import  {getLocalStorageUserInfo} from "../../../static/js/session"
let userRoleId;
if(getLocalStorageUserInfo("enrolleeinfo")[0]){
  userRoleId = getLocalStorageUserInfo("enrolleeinfo")[0].userRoleId;
}


export function getAuthNavChildList(){
  if("SupportManager"===userRoleId){ // 客服经理
    return ["fn-user-manage","fn-master-manage","fn-site-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-product-manage","sn-user-list","sn-user-abnormal","sn-master-account","sn-master-authentication","sn-master-business","sn-master-leave","sn-site-list","sn-site-account","sn-site-abnormal","sn-channel-list","sn-channel-subset","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("SupportStaff"===userRoleId){ // 客服专员
    return ["fn-user-manage","fn-master-manage","fn-site-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-product-manage","sn-user-list","sn-user-abnormal","sn-master-account","sn-master-authentication","sn-master-business","sn-master-leave","sn-site-list","sn-site-account","sn-site-abnormal","sn-channel-list","sn-channel-subset","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("OperationalManager"===userRoleId){ // 运营经理
    return ["fn-user-manage","fn-master-manage","fn-site-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-product-manage","sn-user-list","sn-user-abnormal","sn-master-account","sn-master-authentication","sn-master-remind","sn-master-business","sn-master-leave","sn-site-list","sn-site-account","sn-site-abnormal","sn-site-remind","sn-channel-list","sn-channel-remind","sn-channel-subset","sn-operation-data","sn-operation-advertising","sn-operation-msg","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("OperationalStaff"===userRoleId){ // 运营专员
    return ["fn-user-manage","fn-master-manage","fn-site-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-product-manage","sn-user-list","sn-user-abnormal","sn-master-account","sn-master-remind","sn-master-business","sn-master-leave","sn-site-list","sn-site-account","sn-site-abnormal","sn-site-remind","sn-channel-list","sn-channel-remind","sn-channel-subset","sn-operation-data","sn-operation-advertising","sn-operation-msg","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("FinancialManager"===userRoleId){ // 财务经理
    return ["fn-user-manage","fn-master-manage","fn-site-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-finance-manage","fn-product-manage","sn-user-list","sn-master-account","sn-master-remind","sn-master-business","sn-site-list","sn-site-account","sn-site-abnormal","sn-site-remind","sn-channel-list","sn-channel-remind","sn-channel-subset","sn-operation-data","sn-operation-advertising","sn-operation-msg","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("FinancialStaff"===userRoleId){ // 财务专员
    return ["fn-user-manage","fn-master-manage","fn-site-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-finance-manage","fn-product-manage","sn-user-list","sn-master-account","sn-master-remind","sn-master-business","sn-site-list","sn-site-account","sn-site-abnormal","sn-site-remind","sn-channel-list","sn-channel-remind","sn-channel-subset","sn-operation-data","sn-operation-advertising","sn-operation-msg","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("ProductManager"===userRoleId){ // 产品经理
    return ["fn-user-manage","fn-master-manage","fn-site-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-finance-manage","fn-product-manage","sn-user-list","sn-user-abnormal","sn-master-account","sn-master-authentication","sn-master-remind","sn-master-business","sn-master-leave","sn-site-list","sn-site-account","sn-site-abnormal","sn-site-remind","sn-channel-list","sn-channel-remind","sn-channel-subset","sn-operation-data","sn-operation-advertising","sn-operation-msg","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("ProductStaff"===userRoleId){ // 业务专员
    return ["fn-user-manage","fn-master-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-product-manage","sn-user-list","sn-user-abnormal","sn-master-account","sn-master-business","sn-master-leave","sn-site-list","sn-site-account","sn-site-abnormal","sn-site-remind","sn-channel-list","sn-channel-remind","sn-channel-subset","sn-operation-data","sn-operation-advertising","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("SiteManage"===userRoleId){ // 网点管理员
    return ["fn-master-manage","fn-site-manage","fn-order-manage","fn-product-manage","sn-user-list","sn-user-abnormal","sn-master-account","sn-master-authentication","sn-master-business","sn-master-leave","sn-site-list","sn-site-account","sn-site-abnormal","sn-channel-list","sn-channel-remind","sn-channel-subset","sn-operation-data","sn-operation-advertising","sn-operation-msg","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("ChannelManage"===userRoleId){ // 渠道管理员
    return ["fn-user-manage","fn-master-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-product-manage","sn-user-list","sn-user-abnormal","sn-master-account","sn-master-business","sn-site-list","sn-site-account","sn-site-abnormal","sn-site-remind","sn-channel-list","sn-channel-remind","sn-channel-subset","sn-operation-data","sn-operation-advertising","sn-operation-msg","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }else if("Admin"===userRoleId){ // 超级管理员
    return ["fn-user-manage","fn-master-manage","fn-site-manage","fn-channel-manage","fn-operation-manage","fn-order-manage","fn-finance-manage","fn-product-manage","sn-user-list","sn-user-abnormal","sn-master-account","sn-master-authentication","sn-master-remind","sn-master-business","sn-master-leave","sn-site-list","sn-site-account","sn-site-abnormal","sn-site-remind","sn-channel-list","sn-channel-remind","sn-channel-subset","sn-operation-data","sn-operation-advertising","sn-operation-msg","sn-operation-feedback","sn-order-monitoring","sn-order-waitfordistribution","sn-order-underway","sn-order-pending","sn-order-all","sn-finance-property","sn-finance-record","sn-finance-reconciliation","sn-finance-account","sn-finance-abnormalsettlement","sn-product-list","sn-product-classify","sn-product-high","sn-product-details",];
  }
  return [];
}
export function getAuthBTList(){
  if("SupportManager"===userRoleId){ // 客服经理
    return ["bn-user-list-forbidden","bn-user-list-details","bn-user-abnormal-recover","bn-user-abnormal-details","bn-master-account-forbidden","bn-master-account-details","bn-master-account-newaccount","bn-master-authentication-details","bn-master-business-details","bn-site-list-details","bn-channel-list-details","bn-channel-subset-edit","bn-channel-subset-details","bn-operation-data-details","bn-operation-advertising-apply","bn-operation-advertising-edit","bn-operation-advertising-new","bn-operation-advertising-delete","bn-operation-msg-new","bn-order-all-dispose","bn-order-all-new","bn-order-all-batch","bn-order-all-details","bn-order-all-changemaster","bn-order-all-fine","bn-order-all-changetime","bn-order-all-refund","bn-order-all-remark","bn-order-all-newproduct","bn-order-all-complaints","bn-order-all-send","bn-order-all-abnormal","bn-finance-property-record","bn-finance-property-record-details","bn-finance-reconciliation-down","bn-finance-account-details","bn-finance-account-edit","bn-finance-abnormalsettlement-againsettle",];
  }else if("SupportStaff"===userRoleId){ // 客服专员
    return ["bn-user-list-forbidden","bn-user-list-details","bn-user-abnormal-details","bn-master-account-details","bn-master-account-newaccount","bn-master-authentication-details","bn-master-business-details","bn-site-list-details","bn-channel-list-details","bn-channel-subset-edit","bn-channel-subset-details","bn-operation-data-details","bn-operation-advertising-apply","bn-operation-advertising-edit","bn-operation-advertising-new","bn-operation-advertising-delete","bn-operation-msg-new","bn-order-all-dispose","bn-order-all-new","bn-order-all-batch","bn-order-all-details","bn-order-all-changemaster","bn-order-all-fine","bn-order-all-changetime","bn-order-all-refund","bn-order-all-remark","bn-order-all-newproduct","bn-order-all-complaints","bn-order-all-send","bn-order-all-abnormal","bn-finance-property-record","bn-finance-property-record-details","bn-finance-reconciliation-down","bn-finance-account-details","bn-finance-account-edit","bn-finance-abnormalsettlement-againsettle",];
  }else if("OperationalManager"===userRoleId){ // 运营经理
    return ["bn-user-list-forbidden","bn-user-list-details","bn-user-abnormal-recover","bn-user-abnormal-details","bn-master-account-forbidden","bn-master-account-details","bn-master-account-remind","bn-master-account-newaccount","bn-master-authentication-details","bn-master-remind-new","bn-master-remind-edit","bn-master-remind-delete","bn-master-business-details","bn-site-list-forbidden","bn-site-list-details","bn-site-account-new","bn-site-abnormal-details","bn-site-remind-new","bn-site-remind-edit","bn-site-remind-delete","bn-channel-list-new","bn-channel-list-forbidden","bn-channel-list-details","bn-channel-remind-new","bn-channel-remind-delete","bn-channel-remind-edit","bn-channel-subset-forbidden","bn-channel-subset-edit","bn-channel-subset-details","bn-operation-data-details","bn-operation-advertising-apply","bn-operation-advertising-edit","bn-operation-advertising-new","bn-operation-advertising-delete","bn-operation-msg-new","bn-order-all-dispose","bn-order-all-new","bn-order-all-batch","bn-order-all-details","bn-order-all-changemaster","bn-order-all-fine","bn-order-all-changetime","bn-order-all-refund","bn-order-all-remark","bn-order-all-newproduct","bn-order-all-complaints","bn-order-all-send","bn-order-all-abnormal","bn-finance-property-record","bn-finance-property-record-details","bn-finance-reconciliation-down","bn-finance-account-details","bn-finance-account-edit","bn-finance-abnormalsettlement-againsettle","bn-product-list-soldout","bn-product-high-edit","bn-product-high-new","bn-product-high-delete","bn-product-details-apply","bn-product-details-edit",];
  }else if("OperationalStaff"===userRoleId){ // 运营专员
    return ["bn-user-list-details","bn-user-abnormal-details","bn-master-account-details","bn-master-business-details","bn-site-list-details","bn-site-abnormal-details","bn-channel-list-details","bn-channel-subset-edit","bn-channel-subset-details","bn-operation-data-details","bn-operation-advertising-apply","bn-operation-advertising-edit","bn-operation-advertising-new","bn-operation-advertising-delete","bn-operation-msg-new","bn-finance-property-record","bn-finance-property-record-details","bn-finance-reconciliation-down","bn-finance-account-details","bn-finance-account-edit","bn-finance-abnormalsettlement-againsettle","bn-product-list-soldout","bn-product-details-apply","bn-product-details-edit",];
  }else if("FinancialManager"===userRoleId){ // 财务经理
    return ["bn-finance-property-record","bn-finance-property-record-details","bn-finance-reconciliation-down","bn-finance-account-details","bn-finance-account-edit","bn-finance-abnormalsettlement-againsettle",];
  }else if("FinancialStaff"===userRoleId){ // 财务专员
    return ["bn-finance-property-record","bn-finance-abnormalsettlement-againsettle",];
  }else if("ProductManager"===userRoleId){ // 产品经理
    return ["bn-user-list-forbidden","bn-user-list-details","bn-user-abnormal-recover","bn-user-abnormal-details","bn-master-account-forbidden","bn-master-account-details","bn-master-account-remind","bn-master-account-newaccount","bn-master-authentication-details","bn-master-remind-new","bn-master-remind-edit","bn-master-remind-delete","bn-master-business-details","bn-site-list-forbidden","bn-site-list-details","bn-site-account-new","bn-site-abnormal-details","bn-site-remind-new","bn-site-remind-edit","bn-site-remind-delete","bn-channel-list-new","bn-channel-list-forbidden","bn-channel-list-details","bn-channel-remind-new","bn-channel-remind-delete","bn-channel-remind-edit","bn-channel-subset-forbidden","bn-channel-subset-edit","bn-channel-subset-details","bn-operation-data-details","bn-operation-advertising-apply","bn-operation-advertising-edit","bn-operation-advertising-new","bn-operation-advertising-delete","bn-operation-msg-new","bn-order-all-dispose","bn-order-all-new","bn-order-all-batch","bn-order-all-details","bn-order-all-changemaster","bn-order-all-fine","bn-order-all-changetime","bn-order-all-refund","bn-order-all-remark","bn-order-all-newproduct","bn-order-all-complaints","bn-order-all-send","bn-order-all-abnormal","bn-finance-property-record","bn-finance-property-record-details","bn-finance-reconciliation-down","bn-finance-account-details","bn-finance-account-edit","bn-finance-abnormalsettlement-againsettle","bn-product-list-soldout","bn-product-high-edit","bn-product-high-new","bn-product-high-delete","bn-product-details-apply","bn-product-details-edit",];
  }else if("ProductStaff"===userRoleId){ // 业务专员
    return [];
  }else if("SiteManage"===userRoleId){ // 网点管理员
    return ["bn-master-account-forbidden","bn-master-account-details","bn-master-account-newaccount","bn-master-authentication-details","bn-master-business-details","bn-site-list-forbidden","bn-site-list-details","bn-site-account-new","bn-site-abnormal-details","bn-order-all-details",];
  }else if("ChannelManage"===userRoleId){ // 渠道管理员
    return ["bn-user-list-forbidden","bn-user-list-details","bn-user-abnormal-recover","bn-user-abnormal-details","bn-channel-list-new","bn-channel-list-forbidden","bn-channel-list-details","bn-channel-remind-new","bn-channel-remind-delete","bn-channel-remind-edit","bn-channel-subset-forbidden","bn-channel-subset-edit","bn-channel-subset-details","bn-operation-data-details","bn-operation-advertising-apply","bn-operation-advertising-edit","bn-operation-advertising-new","bn-operation-advertising-delete","bn-operation-msg-new",];
  }else if("Admin"===userRoleId){ // 超级管理员
    return ["bn-user-list-forbidden","bn-user-list-details","bn-user-abnormal-recover","bn-user-abnormal-details","bn-master-account-forbidden","bn-master-account-details","bn-master-account-remind","bn-master-account-newaccount","bn-master-authentication-details","bn-master-remind-new","bn-master-remind-edit","bn-master-remind-delete","bn-master-business-details","bn-site-list-forbidden","bn-site-list-details","bn-site-account-new","bn-site-abnormal-details","bn-site-remind-new","bn-site-remind-edit","bn-site-remind-delete","bn-channel-list-new","bn-channel-list-forbidden","bn-channel-list-details","bn-channel-remind-new","bn-channel-remind-delete","bn-channel-remind-edit","bn-channel-subset-forbidden","bn-channel-subset-edit","bn-channel-subset-details","bn-operation-data-details","bn-operation-advertising-apply","bn-operation-advertising-edit","bn-operation-advertising-new","bn-operation-advertising-delete","bn-operation-msg-new","bn-order-all-dispose","bn-order-all-new","bn-order-all-batch","bn-order-all-details","bn-order-all-changemaster","bn-order-all-fine","bn-order-all-changetime","bn-order-all-refund","bn-order-all-remark","bn-order-all-newproduct","bn-order-all-complaints","bn-order-all-send","bn-order-all-abnormal","bn-finance-property-record","bn-finance-property-record-details","bn-finance-reconciliation-down","bn-finance-account-details","bn-finance-account-edit","bn-finance-abnormalsettlement-againsettle","bn-product-list-soldout","bn-product-high-edit","bn-product-high-new","bn-product-high-delete","bn-product-details-apply","bn-product-details-edit",];
  }
  return [];
}
var getAuthNavChildList=getAuthNavChildList();
export let isShowFunObj={
//后台用户列表  start
    isUserNavChild(key){
      let newArr=getAuthNavChildList, flag=false;
      newArr.forEach(v=>{
        if(key===v){
          flag = true;
        }
      });
      return flag;
    },
};
var getAuthBTList=getAuthBTList()
export let isButtonObj={
  isButtonFun(key){
    let newArr=getAuthBTList, flag=false;
    newArr.forEach(v=>{
      if(key===v){
        flag = true;
      }
    });
    return flag;

  }
};

